-- public.business_pages definition

-- Drop table

-- DROP TABLE business_pages;

CREATE TABLE business_pages (
	page_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	html text NULL,
	businesses_id int4 NULL,
	CONSTRAINT business_pages_pkey PRIMARY KEY (page_id),
	CONSTRAINT fk_businesses FOREIGN KEY (businesses_id) REFERENCES businesses(businesses_id)
);