insert into searches (cert_type, body) values
('E8a', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "E8a": "Y", "State": ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "MP", "AA", "AE", "AP"]}'),
('E8a', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "E8a": "Y", "State": ["NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]}'),
('HubCert', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "HubCert": "Y", "State": ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "MP", "AA", "AE", "AP"]}'),
('HubCert', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "HubCert": "Y", "State": ["NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]}'),
('edwosb', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "edwosb": "Y", "State": ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "MP", "AA", "AE", "AP"]}'),
('edwosb', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "edwosb": "Y", "State": ["NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]}'),
('wosb', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "wosb": "Y", "State": ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "AA", "AE", "AP"]}'),
('wosb', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "wosb": "Y", "State": ["LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR"]}'),
('wosb', '{"NumberOfRows":"99999999", "FirmListColumns": "I38,I18", "FirmListColumnNamesHidden": "Name+and+Trade+Name+of+Firm;UEI", "FirmListColumnNamesDisplay": "Name+and+Trade+Name+of+Firm;+UEI", "wosb": "Y", "State": ["RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]}')